[package]
name = "roli-trade-ad-automation"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
aes-gcm = "0.10"
base64 = "0.21"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
rand = "0.8"
roli = "0.7.2"
rusqlite = { version = "0.30", features = ["bundled"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
windows = { version = "0.48", features = ["Win32_Foundation", "Win32_Security_Cryptography"] }